### ISSUE TITLE
New Rule for format masks (eg for to_date)

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-and-sql-coding-guidelines#100]
When using to_date with a format mask I think most people assume that the format mask is enforced ... which it isnt (see attached screenshot).
Also leaving out numbers wont always result in an exception.

So my suggestion would be to always use ‚FX‘ in front of a format mask to enforce the mask except you need it to be ‚fuzzy‘.
See docs:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Format-Models.html#GUID-7FF68D9E-C7E2-4CA1-9DDB-5CC7169EEEEA

![IMG_7992](https://user-images.githubusercontent.com/8007734/106391048-a6b0c880-63eb-11eb-9f0c-fcd4ffca3b39.jpeg)

**Comment by kibeha** [comment]
True, many are not aware of these rules:
https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/Format-Models.html#GUID-5B755E80-3CB2-4901-BBCF-F0FC764E0BB5

> The following additional formatting rules apply when converting string values to date values (unless you have used the FX or FXFM modifiers in the format model to control exact format checking):
> 
> You can omit punctuation included in the format string from the date string if all the digits of the numerical format elements, including leading zeros, are specified. For example, specify 02 and not 2 for two-digit format elements such as MM, DD, and YY.
> 
> You can omit time fields found at the end of a format string from the date string.
> 
> You can use any non-alphanumeric character in the date string to match the punctuation symbol in the format string.
> 
> If a match fails between a datetime format element and the corresponding characters in the date string, then Oracle attempts alternative format elements, as shown in Table 2-20.

Such a rule can make sense, yes.
