### ISSUE TITLE
Building own validator on top of SQL Developer extension 4.0

### ISSUE THREAD

**Issue by mhoys** [Trivadis/plsql-and-sql-coding-guidelines#107]
Hello,
We would like to build our own PL/SQL validator as an extension of the existing SQL Developer version 4 plug-in. Is there any documentation explaining how to do this? With some sample code?

Thanks
Matthias

**Comment by PhilippSalvisberg** [comment]
> Is there any documentation explaining how to do this? With some sample code?

Yes, see https://github.com/Trivadis/plsql-cop-validators

**Comment by mhoys** [comment]
Great, thanks!
