### ISSUE TITLE
Question: Handling of column aliases?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [Trivadis/plsql-and-sql-coding-guidelines#108]
I looked at your PDF with the "Guidelines", and the word "alias" only exists once. Do I see it right that you don't "handle" them? 

I had a setting, mentioned by ThatJeffSmith, which aligns and highlight the aliases. Can it be combined with your settings?

**Comment by kibeha** [comment]
Hi, Pierre

Correct that the guidelines only have a rule about _table_ aliases (not _column_ aliases):
G-3120: Always use table aliases when your SQL statement involves more than one source.

The guidelines as such are about best practices / coding style for writing SQL and PL/SQL code, not really about tool settings ("handling").
For such settings you can see https://github.com/Trivadis/plsql-formatter-settings which are settings that try to implement these guideline rules as closely as possible. I think you can add your own settings too, if you wish, but maybe @PhilippSalvisberg can answer that question.

For the guidelines themselves, highlighting and such is not relevant. It might be that the guidelines could use one or more rules on column aliases. But a rule like for example "Always use column aliases" probably wouldn't be a good idea - >90% of the time the column names don't need to be aliased.

Perhaps could include a rule for "Always align column aliases if used" for readability? Or other similar rules for good practice concerning use of column aliases in SQL (not formatting as such.) If you have opinions on good rules, please post them and we can consider including them (or not) in future versions of the guidelines. Thanks.

**Comment by Pierre-de-la-Verre** [comment]
I tried to find my sources in the fragments of my settings - and failed (at the moment). I'm not sure, but I think that ..

- the column-highlighting is from Philipp himself, called " PlSqlColTabAlases"
- the alignment is maybe from Vadim, maybe here https://community.oracle.com/tech/developers/discussion/4298336/column-alias-alignment-in-sql-developer  or here:  https://vadimtropashko.wordpress.com/2017/01/03/custom-formatting-in-sqldev-4-2/

**Comment by PhilippSalvisberg** [comment]
SQLDev's default configuration highlights column and table aliases.

As Kim mentioned we maintain a GitHub repo with formatter settings. It's based on the SQLDev's settings with a few modifications. There is also a fix for alignments of table aliases (see https://github.com/Trivadis/plsql-formatter-settings/blob/sqldev-20.4.1/settings/sql_developer/trivadis_custom_format.arbori#L1210 and the associated issue https://github.com/Trivadis/plsql-formatter-settings/issues/54).

Highlighting and formatting are two different features in SQLDev and can be configured independently.

If you have questions about these features in general, I recommend asking them in the SQLDev forum.

**Comment by kibeha** [comment]
As this was more a highlighting/formatting question than an issue with the Guidelines as such, I'm closing this issue.
If any ideas about new rules to the Guidelines concerning the best practices of using column aliases, feel free to submit idea issues and it'll be considered for future releases of the Guidelines.
