### ISSUE TITLE
Visualization issues with new guidelines 4.1

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-and-sql-coding-guidelines#123]
Here's a screenshot that shows the issues:

![image](https://user-images.githubusercontent.com/3883171/179676839-8d2d4f8f-434c-4f2e-8b1e-652678bf42a1.png)

The first one shows that a backslash is shown before the star in `db* Codecop`.

The second one shows that the logo is positioned unfortunate. It should be positioned a bit higher with a smaller margin to the top.

I assume the second issue is caused by the configuration of Material for MkDocs. I think I've solved that for the snapshot version. See https://philippsalvisberg.github.io/plsql-and-sql-coding-guidelines/main/3-coding-style/coding-style/#formatting . Heres a screenshot:

![image](https://user-images.githubusercontent.com/3883171/179677757-37670d4e-2f71-4ce2-9d49-840e5c2fa733.png)

The first issue looks like an escaping issue. Either in the source or in Material for MkDocs.

**Comment by kibeha** [comment]
Thanks for finding the configuration resolution of issue 2.

As for issue 1, I suspect mkdocs bug in rendering of menu from page titles, but what's weird is that the same mkdocs is the basis of the generated pdf, where the escaped asterisk work fine in generated TOC from page titles.

Workaround would be to not use escaping backslash in these page titles - in this case there will be no inadvertent emphasized text because there is only a single asterisk, so it will work. But I'll research mkdocs a bit to see if it's a known issue.

**Comment by PhilippSalvisberg** [comment]
Issue 2 is caused by using a different version of Material for MkDocs. The configuration files require MkDocs for Material 6.2.8 (at least they are tested with this version).

In https://philippsalvisberg.github.io/plsql-and-sql-coding-guidelines/main/ the versions are:

`<meta name="generator" content="mkdocs-1.1.2, mkdocs-material-6.2.8">`

In https://trivadis.github.io/plsql-and-sql-coding-guidelines/v4.1/  the versions are:

`<meta name="generator" content="mkdocs-1.1.2, mkdocs-material-6.0.2">`

This is based on using different version of `trivadis/mktools`. See https://hub.docker.com/r/trivadis/mktools/tags . For each of these tags there is also a tag in this repo starting with `mktools-`.  The following table shows the docker image tags and their included versions for MkDocs and Material for MkDocs:

mktools docker tag | versions
-- | --
mktools-1.0 | mkdocs-1.0.4, mkdocs-material:4.4.2
mktools-2.0 | mkdocs-1.1.2, mkdocs-material-5.5.14
mktools-2.1 | mkdocs-1.1.2, mkdocs-material-6.0.0
mktools-2.2 | mkdocs-1.1.2, mkdocs-material-6.0.2
mktools-3.0 | mkdocs-1.1.2, mkdocs-material-6.2.8

The [`Dockerfile`](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/blob/main/docker/Dockerfile) shows also that the latest version uses mkdocs-awesome-pages-plugin-2.5.0, pymdown-extensions-8.1.1 and mike-0.5.5. 

It's probably time to update these dependencies. Maybe this solves issue 1. However, this might need more time. In the meantime I suggest to rebuild the static web sites using `mktools-3.0`. To enforce the usage of the latest trivadis/mktools Docker image, the `latest` tag must be removed locally, like this:

`docker rmi trivadis/mktools:latest`.

**Comment by PhilippSalvisberg** [comment]
fixed via 8a4cdc657b7519e29076c1cc7976bcf5ac6851b4 . Generated and deployed site for v4.1 and main (4.2-SNAPSHOT).
