### ISSUE TITLE
Mention "PL/SQL & SQL Formatter Settings" in "Tool Support" chapter 

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-and-sql-coding-guidelines#124]
The tool support chapter was reworked and extended in v4.1 via #8 and #9.

IMO it would be nice to mention https://github.com/Trivadis/plsql-and-sql-coding-guidelines as well. Especially since it is used to automatically format all code in this repo.

**Comment by kibeha** [comment]
Agreed. https://github.com/Trivadis/plsql-formatter-settings should get a mention in next guideline version.
