### ISSUE TITLE
Make the latest release downloadable from GitHub pages

### ISSUE THREAD

**Issue by mmarquezvacas** [Trivadis/plsql-and-sql-coding-guidelines#16]
I was looking for version 3.3 in PDF to download it. But only can download 3.4-SNAPSHOT. 
¿Is there any chance to have the PDF in the Releases section?
Great work!

**Comment by mmarquezvacas** [comment]
Sorry, I found the latest PDF inside this file: [https://codeload.github.com/Trivadis/plsql-and-sql-coding-guidelines/zip/v3.3](url)

**Comment by PhilippSalvisberg** [comment]
You can get the file also here: https://github.com/Trivadis/plsql-and-sql-coding-guidelines/blob/8764f371f51f2d2defab1f355aaf5d867ad435fb/PLSQL-and-SQL-Coding-Guidelines.pdf . 

You can get there via [releases](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/releases), click on [8764f37](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/commit/8764f371f51f2d2defab1f355aaf5d867ad435fb) and then on [Browse Files](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/tree/8764f371f51f2d2defab1f355aaf5d867ad435fb). Then you see the repository as it was at release time.

However, I plan to remove the .pdf file from the source repository in future. See also issue #13 .
