### ISSUE TITLE
Trivadis Oracle SQL Developer Extension for latest release

### ISSUE THREAD

**Issue by mmarquezvacas** [Trivadis/plsql-and-sql-coding-guidelines#17]
Hi, i was wondering if you're going to release PL/SQL Cop for SQL Developer free extension for Trivadis PL/SQL &  SQL Coding Guidelines Version 3.3 (latest release).

**Comment by PhilippSalvisberg** [comment]
Future version of the extension will link to the guidelines on the GitHub pages. However, this repository manages the guidelines only. Please as your questions regarding PL/SQL Cop in [this forum](https://www.salvis.com/blog/forum/plsql-cop/). Thank you.
