### ISSUE TITLE
CASE / WHEN is indentend backwards

### ISSUE THREAD

**Issue by chatelao** [Trivadis/plsql-and-sql-coding-guidelines#198]
IS:
- In my CASE / WHEN statements, the "WHEN" part is indented backwards:

```sql
SELECT job_id
     , CASE
   WHEN job_id = 'AD_PRES' THEN '123'
   WHEN job_id = 'IT_PROG' THEN '456'
   ELSE '059'
         END case_test
  FROM employees
```

WOULD LIKE:
- The WHEN parts to be aligned or even indeted too:

```sql
SELECT job_id
     , CASE
        WHEN job_id = 'AD_PRES' THEN '123'
        WHEN job_id = 'IT_PROG' THEN '456'
        ELSE '059'
       END case_test
  FROM employees
```

**Comment by PhilippSalvisberg** [comment]
This repository manages the guidelines for code style in this section: https://trivadis.github.io/plsql-and-sql-coding-guidelines/v4.2/3-coding-style/coding-style/ . 

If you are using our formatter settings for SQL Developer then please post an issue in this repo: https://github.com/Trivadis/plsql-formatter-settings . If you are using other setting then please contact the ventor of your IDE. Thanks.

**Comment by chatelao** [comment]
Danke, mache ich doch gerne.
