### ISSUE TITLE
Missing "G-"-prefix in pagetitle for rule G-7320

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#20]
In the title of the page for rule G-7320 (https://trivadis.github.io/plsql-and-sql-coding-guidelines/4-language-usage/7-stored-objects/3-procedures/g-7320/) the "G-"-prefix is missing for the rule-number.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. 

The prefix `G-` is missing in [g-7320.md](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/blob/master/docs/4-language-usage/7-stored-objects/3-procedures/g-7320.md).
