### ISSUE TITLE
Incomplete example-code in page for rule G-8410

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#21]
On the page for rule G-8510 (https://trivadis.github.io/plsql-and-sql-coding-guidelines/4-language-usage/8-patterns/4-ensure-single-execution-at-a-time-of-a-program-unit/g-8410/)
the example-code is incomplete:

- in the code-window "Example (bad)" is the code for the package used in the code-window "Example (good)"

- therefore a bad code-example is missing

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. Yes, this is a bug. The bad example is missing also in the original guidelines v3.2. - We need to create one.
