### ISSUE TITLE
G-8310 value_error good_example

### ISSUE THREAD

**Issue by PrzemekFilipiak** [Trivadis/plsql-and-sql-coding-guidelines#211]
Hi,
Changing variable declarion to default will raise "value_error" if in_dept_name := null
create or replace package body department_api is
   function dept_by_name( -- NOSONAR: non-deterministic
      in_dept_name in departments.department_name%type
   )
      return departments%rowtype is
  --  co_dept_name constant departments.department_name%type not null := in_dept_name;
      co_dept_name departments.department_name%type not null default 'example department_name';
      r_return     departments%rowtype;
   begin
      -- get the department by name
      <<trap>>
      begin
        co_dept_name := in_dept_name; -- if in_dept_name := null, will raise "value_error"
         select *
           into r_return
           from departments
          where department_name = co_dept_name;
         return r_return;
      exception
         when no_data_found then
            return null;
         when too_many_rows then
            raise;
         when value_error then
            handle_error;
      end trap;
   end dept_by_name;
end department_api;
/

![G_8310_good_example](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/assets/92021552/8bb4224e-f217-4d3c-b470-3f7d6e0b9d15)

**Comment by PhilippSalvisberg** [comment]
Could you please elaborate how your change of the good example code in [G-8310](https://trivadis.github.io/plsql-and-sql-coding-guidelines/main/4-language-usage/8-patterns/3-validating-input-parameter-size/g-8310/#example-good) is related to this guideline?

What kind of change are you suggesting?

Regarding your code change. You changed a constant to a variable with a default value. If you would like to accept a null value you have to get rid of the `NOT NULL` in the declaration. However, this is not related to the G-8310 IMO.

**Comment by PrzemekFilipiak** [comment]
Hi,
“PL/SQL & SQL Coding Guidelines Reason
This technique raises an error (value_error) which may not be handled in the called program unit. “
In my opinion above sentence is not true, because you could catch “value_error” when:
variable in declaration section will be “not null default”.
Example:
![G_8310](https://github.com/Trivadis/plsql-and-sql-coding-guidelines/assets/92021552/93545d06-a036-4052-a6c6-45bee745788d)

**Comment by PhilippSalvisberg** [comment]
In your example, you are assigning the parameter to a variable in the body and not in the declare section. Hence you are not following the guideline G-8310. 

> G-8310: Always validate input parameter size by assigning the parameter to a size limited variable in the declaration section of program unit.
