### ISSUE TITLE
Plans to introduce similar guidelines for Postgres PL/pgSQL

### ISSUE THREAD

**Issue by MrUrdam** [Trivadis/plsql-and-sql-coding-guidelines#219]
Hey

I recently came over this guidlines for Oracles PL/SQL.
You have created something very useful.

Because I am switching over to PostgreSQL and PL/pgSQL at the moment, I just wanted to ask if you know about something similar for it. Or maybe plan to create soemthing like this for PL/pgSQL. 

A big advantage of your guidlines is your creation of your PL/SQL code analysis tool. Something like this would be awesome for PL/pgSQL aswell.

Feel free to comment with your opinion about this. 

Best regards

Andre

**Comment by PhilippSalvisberg** [comment]
>I recently came over this guidlines for Oracles PL/SQL.
>You have created something very useful.

Thank you. 

>Because I am switching over to PostgreSQL and PL/pgSQL at the moment, I just wanted to ask if you know about something similar for it. 

Here are some links that may contain relevant information:

- https://giswiki.hsr.ch/SQL_and_PL/pgSQL_Programming_Style_Guide
- https://ledgersmb.org/community-guide/community-guide/development/coding-guidelines/plpgsql-coding-guidelines
- https://www.sqlstyle.guide/ (SQL in general)
- https://www.postgresql.org/docs/current/plpgsql-implementation.html (regarding naming PL/pgSQL variables)

>Or maybe plan to create soemthing like this for PL/pgSQL.

We do not plan to extend this repository to cover PL/pgSQL. 

>A big advantage of your guidlines is your creation of your PL/SQL code analysis tool. Something like this would be awesome for PL/pgSQL aswell.

I agree.
