### ISSUE TITLE
New Rule: no ROWNUM in same query level as ORDER BY

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#26]
**Language Usage / DML & SQL / General**
Never use ROWNUM at the same query level as ORDER BY

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-4062?search=ROWNUM%20at%20the%20same%20query%20level%20as%20ORDER%20BY):

Oracle's ROWNUM is a pseudo column that numbers the rows in a result set. Unfortunately, it numbers the rows in the set before ordering is applied. So combining the two in the same query won't get you the results you expect. Instead, you should move your selection and ordering into a subquery, and use ROWNUM only on the outer query.

**Noncompliant Code Example**
```
SELECT fname, lname, deptId
FROM employee
WHERE rownum <= 10
ORDER BY salary  -- Noncompliant
```

**Compliant Solution**
```
SELECT *
FROM ( SELECT fname, lname, deptId
    FROM employee
    ORDER BY salary
  )
WHERE rownum <= 10
```

**Comment by PhilippSalvisberg** [comment]
makes sense.
