### ISSUE TITLE
New Rule: no identical expressions on both sides of a binary operator

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#28]
**Language Usage / General**
Never use the same expression on both sides of a relational comparison operator or a logical operator

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-1764?search=Identical%20expressions%20should%20not%20be%20used%20on%20both%20sides%20of%20a%20binary%20operator):

**Identical expressions should not be used on both sides of a binary operator**

Using the same value on either side of a binary operator is almost always a mistake. In the case of logical operators, it is either a copy/paste error and therefore a bug, or it is simply wasted code, and should be simplified.

This rule ignores operators +, * and ||, and expressions: 1=1, 1<>1, 1!=1, 1~=1 and 1^=1.

**Noncompliant Code Example**
```
SELECT code
  FROM Person
  WHERE first_name IS NULL OR first_name IS NULL; -- Noncompliant

SELECT * FROM Users
  INNER JOIN Clients ON Clients.id = Clients.id; -- Noncompliant
```

**Compliant Solution**
```
SELECT code
  FROM Person
  WHERE first_name IS NULL OR last_name IS NULL;

SELECT * FROM Users
  INNER JOIN Clients ON Clients.id = Users.id;
```

**Comment by PhilippSalvisberg** [comment]
makes sense.
