### ISSUE TITLE
New Rule: values for NOT NULL columns in INSERT statements

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#29]
**Language Usage / DML & SQL /General**
Always include values for NOT NULL Columns in an INSERT statement

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-3618?search=Inserts%20should%20include%20values%20for%20non-null%20columns);

**Inserts should include values for non-null columns**

Any insert which omits a value for a NOT NULL column in a database table will be automatically rejected by the database unless a default value has been specified for the column.

**Noteworthy**

This rule raises issues only when a Data Dictionary is provided during the analysis. See https://docs.sonarqube.org/display/PLUG/Data+Dictionary

**Noncompliant Code Example**

With the table MY_TABLE having a NOT NULL column N2 without default value and a NOT NULL column N3 with default value:
```
  INSERT INTO MY_TABLE  -- Noncompliant; N2 value omitted
  (
    N1
  )
  VALUES
  (
    1
  )
```

**Compliant Solution**
```
  INSERT INTO MY_TABLE  -- Compliant even though N3 value not supplied
  (
    N1,
    N2
  )
  VALUES
  (
    1,
    'Paul'
  )
```

**Comment by PhilippSalvisberg** [comment]
This is certainly true. However, such kind of errors are hardly missed. The first run of such a `INSERT` statement will cause an error. Additionally, the check requires data dictionary information. This is not available for PL/SQL Cop and is beyond static SQL or PL/SQL code analysis.
