### ISSUE TITLE
New Rule: assign OUT-parameters

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#30]
**Language Usage / Stored Objects / Procedures**
Always assign values to OUT parameters

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-4196?search=out%20parameter):

**Output parameters should be assigned**

Marking a parameter for output means that callers will expect its value to be updated with a result from the execution of the procedure. Failing to update the parameter before the procedure returns is surely an error.

**Noncompliant Code Example**
```
CREATE OR REPLACE PROCEDURE greet(
  name     IN  VARCHAR2,
  greeting OUT VARCHAR2) -- Noncompliant
AS
  message VARCHAR2(45);
BEGIN
  SELECT 'Hello ' || RTRIM(name) INTO message FROM DUAL;
END;
```

**Compliant Solution**
```
CREATE OR REPLACE PROCEDURE greet(
  name     IN  VARCHAR2,
  greeting OUT VARCHAR2)
AS
BEGIN
  SELECT 'Hello ' || RTRIM(name) INTO greeting FROM DUAL;
END;
```

**Comment by PhilippSalvisberg** [comment]
makes sense.

Considerations for PL/SQL Cop check:
All kind of assignments must be considered. However, this is difficult, e.g. when another procedure is called and this output parameter is passed. An option could be to assume that when the output parameter is used in a function / procedure call, then it is assigned there.
