### ISSUE TITLE
New Rule: assign strings only to variables / columns with adequate size

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#32]
**Language Usage / Variables & Types / Character Data Types**
Never assign a string to a variable or column that is to small to hold it

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-3921?search=Strings%20should%20only%20be%20moved%20to%20variables%20or%20columns%20which%20are%20large%20enough%20to%20hold%20them):

**Strings should only be moved to variables or columns which are large enough to hold them**

Trying to assign a large character value to a smaller variable or column will raise an error.

**Noncompliant Code Example**
```
create table persons (id number, name varchar2(4));

insert into persons (id, name) values (1, 'Alice'); -- Noncompliant, raises ORA-12899

create or replace procedure sp1
is
  foo varchar2(2);
begin
  select name into foo from persons where id = 1; -- Noncompliant, may raise ORA-06502
end;
```

**Compliant Solution**
```
create table persons (id number, name varchar2(8));

insert into persons (id, name) values (1, 'Alice');

create or replace procedure sp1
is
  foo varchar2(8);
begin
  select name into foo from persons where id = 1;
end;
```

**Comment by PhilippSalvisberg** [comment]
This rule requires data dictionary information. This is beyond the scope of this guidelines. Similar as for #24, #29.
