### ISSUE TITLE
New Rule: never repeat unary operators

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#33]
**Language Usage / General**
Never repeat an unary operator multiple times
(happens often as a typo or caused by lack of consentration)

bad:
`l_value := ++5`
`IF l_boolean IS NOT NOT TRUE `

good:
`l_value := +5`
`IF l_boolean IS NOT TRUE `

**Comment by PhilippSalvisberg** [comment]
I ran the following test on my 19c database instance:

```
set echo on
set serveroutput on
declare
   l_test number;
begin
   l_test := ++1;
   dbms_output.put_line(l_test);
end;
/
select ++1 from dual;
```

The result was:
```
SQL> set echo on
SQL> set serveroutput on
SQL> declare
  2     l_test number;
  3  begin
  4     l_test := ++1;
  5     dbms_output.put_line(l_test);
  6  end;
  7  /
1


PL/SQL procedure successfully completed.

SQL> select ++1 from dual;

Error starting at line : 10 in command -
select ++1 from dual
Error at Command Line : 10 Column : 9
Error report -
SQL Error: ORA-00936: missing expression
00936. 00000 -  "missing expression"
*Cause:    
*Action:
```

Using repeated unary operators seems to be possible for PL/SQL only. In SQL this leads to an error, which I consider good. As long as the PL/SQL parser is not able to detect this kind of errors, an additional rule makes sense.

**Comment by PhilippSalvisberg** [comment]
@silviomarghitola Is this a SonarSource rule? I could not find it.

**Comment by PhilippSalvisberg** [comment]
I checked our PL/SQL parser. This:

```
declare
   l_test number;
begin
   l_test := ++1;
   dbms_output.put_line(l_test);
end;
/
``` 

leads to a parse error at line 4, column 16. From my point of view this is correct. In fact I think for this case an Oracle SR should be opened instead of adding a rule and fixing the parser to support "wrong" syntax.
