### ISSUE TITLE
New Rule: don't self-assign variables or columns

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#34]
**Language Usage / General**
never assign a column or variable to itself

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-1656?search=Variables%20and%20columns%20should%20not%20be%20self-assigned):

**Variables and columns should not be self-assigned**

here is no reason to re-assign a variable to itself. Either this statement is redundant and should be removed, or the re-assignment is a mistake and some other value or variable was intended for the assignment instead.

**Noncompliant Code Example**
```
UPDATE person
SET name = name;
```

**Compliant Solution**
```
UPDATE person
SET name = UPPER(name);
```

**Comment by PhilippSalvisberg** [comment]
makes sense.

Notes: All assignments should be considered for the PL/SQL Cop check.

**Comment by RichardSoule** [comment]
As an aside, one exception would be when attempting to fire cross edition triggers when using Edition Based Redefinition. You may (or may not) want to include that exception.

**Comment by kibeha** [comment]
Made it two rules:
- One for variable self-assignment using "Never".
- One for column self-assignment using "Avoid" and mentioning the trigger firing exception.
