### ISSUE TITLE
New Rule: never only execute a RAISE within an exeption handler

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#37]
**Language Usage / Exception Handling**
Avoid "EXCEPTION WHEN ... THEN" clauses that only execute a RAISE
(if this rule gets implementet, the good-example of rule G-5060 needs to be changed)

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-2737?search=RAISE%20within%20an%20exeption%20):

**"EXCEPTION WHEN ... THEN" clauses should do more than "RAISE"**

An EXCEPTION WHEN ... THEN clause that only rethrows the caught exception has the same effect as omitting the EXCEPTION clause altogether and letting it bubble up automatically, but with more code and the additional detriment of leaving maintainers scratching their heads.

Such clauses should either be eliminated or populated with the appropriate logic.

**Noncompliant Code Example**
```
BEGIN
  SELECT 1/0;
EXCEPTION
  WHEN ZERO_DIVIDE THEN
    RAISE; -- Noncompliant
  WHEN OTHERS THEN
    RAISE; -- Noncompliant
END;
```

**Compliant Solution**
```
BEGIN
  SELECT 1/0;
EXCEPTION
  WHEN ZERO_DIVIDE THEN  -- Compliant: handles 'division by zero' error
    -- do something to manage the division by zero
    COMMIT;

  WHEN OTHERS THEN
    ROLLBACK;
END;
```

**Comment by PhilippSalvisberg** [comment]
I do not agree with this rule. While it is true that this is mimicking the default behaviour, such an explicit raise documents that it is wanted. As mentioned, it contradicts also our rule [G-5060](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/5-exception-handling/g-5050/).
