### ISSUE TITLE
New Rule: no RETURN within a loop

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#39]
**Language Usage / Control Structures / Flow Control**
Avoid using RETURN from within a loop

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-2538?search=%22RETURN%22%20should%20not%20be%20used%20from%20within%20a%20loop):

**"RETURN" should not be used from within a loop**

RETURN should not be used from within a FOR or WHILE loop. Doing so can quickly turn your code into "spaghetti code". Such code is hard to read, refactor and therefore to maintain.

**Deprecated**
This rule is deprecated, and will eventually be removed.

**Comment by PhilippSalvisberg** [comment]
This rule is redundant to [G-7420](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/7-stored-objects/4-functions/g-7420/).
