### ISSUE TITLE
New Rule: WHEN OTHERS as last clause in exception handling

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#41]
**Language Usage / Exception Hadling**
Always use a WHEN OTHERS clause at the end of a EXCEPTION block

**Comment by PhilippSalvisberg** [comment]
from [SonarSource](https://rules.sonarsource.com/plsql/RSPEC-1041):

**"WHEN OTHERS" clauses should be used for exception handling**

Ensure that every possible exception is caught by using a WHEN OTHERS clause.

**Noncompliant Code Example**
```
SET SERVEROUTPUT ON

DECLARE
  result PLS_INTEGER;
  custom_exception EXCEPTION;
BEGIN
  result := 42 / 0;                            -- "Unexpected" division by 0

  RAISE custom_exception;
EXCEPTION                                      -- Non-Compliant
  WHEN custom_exception THEN
    DBMS_OUTPUT.PUT_LINE ('custom_exception: ' || DBMS_UTILITY.FORMAT_ERROR_STACK);
END;
/
```
**Compliant Solution**
```
SET SERVEROUTPUT ON

DECLARE
  result PLS_INTEGER;
  custom_exception EXCEPTION;
BEGIN
  result := 42 / 0;                            -- "Unexpected" division by 0

  RAISE custom_exception;
EXCEPTION                                      -- Compliant
  WHEN custom_exception THEN
    DBMS_OUTPUT.PUT_LINE ('custom_exception: ' || DBMS_UTILITY.FORMAT_ERROR_STACK);
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE ('other: ' || DBMS_UTILITY.FORMAT_ERROR_STACK);
END;
/
```

**Comment by PhilippSalvisberg** [comment]
I do not agree with this rule. This would require every PL/SQL block to handle exceptions, introducing useless code and is working against the default behaviour.

**Comment by silviomarghitola** [comment]
The intention of this rule - from my point of view - is not to handle exceptionsk in every PL/SQL block, but in case there is an EXCEPTION block, there should always be a WHEN OTHERS statement.

**Comment by PhilippSalvisberg** [comment]
I do not think this changes much. 

It is good to not include an exception handler for `OTHERS` when there is not other exception handler. But if you define an other handler you have also to define a handler for `OTHERS`? - What is the reasoning? How is this improving the code?

I agree that there are cases where it really make sense, e.g when you need to catch all exceptions, handle them and log them all. But making this a common rule is a step too much for me.
