### ISSUE TITLE
New Rule: specify columns to ORDER BY explicitly

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#42]
**Language Usage / DML & SQL / General**
Always specify columns in a ORDER BY clause explicitly

**Comment by PhilippSalvisberg** [comment]
from [SonarQube](https://rules.sonarsource.com/plsql/RSPEC-1735)

**Column names should be used in a SQL "ORDER BY" clause**

Even though the ORDER BY clause supports using column numbers, doing so makes the code difficult to read and maintain. Therefore the use of column names is preferred.

**Noncompliant Code Example**

```
BEGIN
  SELECT col2, col3
  BULK COLLECT INTO result
  FROM my_table
  ORDER BY
    1 ASC;           -- Noncompliant - if col1 is added to the selected fields, this may break
END;
/
```

**Compliant Solution**
```
BEGIN
  SELECT col2, col3
  BULK COLLECT INTO result
  FROM my_table
  ORDER BY
    col2 ASC;
END;
/
```

**Comment by PhilippSalvisberg** [comment]
This is a duplicate to [G-3180](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/3-dml-and-sql/1-general/g-3180/)
