### ISSUE TITLE
New Rule: Always specify ORDER direction

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#43]
**Language Usage / DML & SQL / General**
Always specify explicitly the direction in an ORDER BY clause

**Comment by silviomarghitola** [comment]
from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-2530?search=order)

**An "ORDER BY" direction should be specified explicitly**

ASC or DESC should be specified for every column of an ORDER BY clause to improve readability.

**Noncompliant Code Example**

```sql
BEGIN
  SELECT col1, col2, col3
  BULK COLLECT INTO result
  FROM my_table
  ORDER BY
    col1 ASC,
    col2,
    col3 DESC;
END;
```

**Compliant Solution**

```sql
BEGIN
  SELECT col1, col2, col3
  BULK COLLECT INTO result
  FROM my_table
  ORDER BY
    col1 ASC,
    col2 ASC,
    col3 DESC;
END;
```

**Comment by PhilippSalvisberg** [comment]
I do not agree with this rule. My experience is that the default sort option for `ASC` is widely used and does not lead to problems in understanding the code. Introducing such a rule would lead to a lot of violations, forcing developers to change code without really making it better.

If someone does not have a really good reason for some rule I'd like to reject it.

**Comment by S-Koell** [comment]
I would also disagree but I can see an argument for it.
It's similar to specifying the parameter as "IN" in a function/procedure which is regarded as best practice as far as I know. But it is also widely used without.

**Comment by PhilippSalvisberg** [comment]
Thanks @S-Koell. You are referring to [G-7240](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/4-language-usage/7-stored-objects/2-packages/g-7240/) right? I think this guideline is good, but the PL/SQL Cop validator is not consistent. Since it is difficult to determine if a `IN OUT` parameter is really read & write it just checks if `IN` or an `OUT` is defined. This matches the general description of the rule that is better for reader to explicitly defined the mode (recommendation)  but misses the main issue about unnecessary usage of the combined `IN OUT` mode. Again, we have to distinguish between the guidelines an the implementation of the validator. Based on that I think it is consistent to reject this new rule.

**Comment by S-Koell** [comment]
@PhilippSalvisberg Yes, I'm talking about G-7240.
First of all: The title of the guideline and the reason don't really match. The title talks about IN OUT but the reason paragraph talks about specifying IN **OR** OUT.

If the reason paragraph is a valid guideline in your opinion than it perfectly fits in this discussion:
All the arguments for 7240 would apply for this issue:

> By showing the mode of parameters, you help the reader. If you do not specify a parameter mode, the default mode is IN.

By showing the ORDER mode you help the reader ....

> Explicitly showing the mode indication of all parameters is a more assertive action than simply taking the default mode.

Also applies to ORDER BY

> Anyone reviewing the code later will be more confident that you intended the parameter mode to be IN / OUT.

Anyone reviewing will be more confident that you intended ASC / DESC


My conclusion:
For consistency reasons I would be for this rule (if 7240 exists like it does). 

You can always deactivate this rule if you don't like it.  

Regarding the inconsistencies with 7240:
I think that should be fixed. Maybe two rules:
- Avoid using an IN OUT parameter as IN or OUT only
- When specifying parameters always add the parameter mode

**Comment by PhilippSalvisberg** [comment]
We discussed on G-7240 on other occasions.  I agree we have a consistency issue with G-7240. It really should cover just the combined "IN OUT" mode. The description should be changed and the validator amended. Then, parameters without a mode would not violate a guideline.

I'm also for consistency. But my conclusion is different. I suggest to reject this issue and change G-7240 to cover  `IN OUT` mode only.

**Comment by S-Koell** [comment]
> I'm also for consistency. But my conclusion is different. I suggest to reject this issue and change G-7240 to cover IN OUT mode only.

Sure, that would be the other option. As I said my conclusion was based on "if 7240 exists like it does".

 I'm fine with your proposal.
