### ISSUE TITLE
New Rule: no inversion of boolean checks

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#44]
**Language Usage / Control Structures / CASE ...**
Avoid inverting boolean checks

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-1940)

**Boolean checks should not be inverted**

It is needlessly complex to invert the result of a boolean comparison. The opposite comparison should be made instead.

**Noncompliant Code Example**

```sql
IF NOT x <> y THEN
  -- ...
END IF;
```

**Compliant Solution**

```sql
IF x = y THEN
  -- ...
END IF;
```

**Comment by PhilippSalvisberg** [comment]
I agree, the compliant solution is much easier to read.
