### ISSUE TITLE
New Rule: no comparison of boolean variables

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#45]
**Language Usage / Control Structures / CASE ...**
Avoid comparing boolean variables or colums with TRUE or FALSE

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-1125)

**Boolean literals should not be redundant**

Redundant Boolean literals should be removed from expressions to improve readability.

**Noncompliant Code Example**

```sql
DECLARE
  foo BOOLEAN := TRUE;
BEGIN
  IF foo = FALSE THEN
    DBMS_OUTPUT.PUT_LINE('foo = false!');
  ELSIF foo = TRUE THEN
    DBMS_OUTPUT.PUT_LINE('foo = true!');
  END IF;
END;
```

**Compliant Solution**

```sql
DECLARE
  foo BOOLEAN := TRUE;
BEGIN
  IF NOT foo THEN
    DBMS_OUTPUT.PUT_LINE('foo = false!');
  ELSIF foo THEN
    DBMS_OUTPUT.PUT_LINE('foo = true!');
  END IF;
END;
```

**Comment by PhilippSalvisberg** [comment]
makes sense.
