### ISSUE TITLE
New Rule: no compound triggers with only one triggers within

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#47]
**Language Usage / Stored Objects / Triggers**
Avoid compound triggers that have only one trigger implemented

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-1056)

**Compound triggers should define at least two triggers**

Compound triggers were introduced to ease the implementation of multiple triggers which need to work in cooperation.

Typically, a FOR EACH ROW trigger accumulates facts, and an AFTER STATEMENT trigger performs the actual changes.

The compound trigger can hold a state common to all the triggers it defines, thereby removing the need to use package variables. This approach is sometimes the only possible one, as when avoiding a mutating table ORA-04091 error, or it can be used to get better performance.

However, there is no point in defining a compound trigger which contains only a single trigger, since there is no state to be shared. In such cases, a simple trigger should be used instead.

**Noncompliant Code Example**

```sql
CREATE OR REPLACE TRIGGER my_trigger
FOR INSERT ON my_table
COMPOUND TRIGGER

AFTER EACH ROW IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('New row inserted!');
END AFTER EACH ROW;

END;
```

**Compliant Solution**

```sql
CREATE OR REPLACE TRIGGER my_trigger
  AFTER INSERT
  ON my_table
  FOR EACH ROW
BEGIN
  DBMS_OUTPUT.PUT_LINE('New row inserted!');
END;
```

**Comment by PhilippSalvisberg** [comment]
But why exactly is this a bad thing? What do others think?

**Comment by rogertroller** [comment]
The only reason i see is, that in this case you have to look into the trigger to see when it fires, whereas with a conventional trigger you see it in the trigger specs or when using a decent naming convention you can derive it from the name.

And...it is more code so more lines for the interpreter.

**Comment by PhilippSalvisberg** [comment]
@rogertroller That means that you agree with the rule, right?

**Comment by rogertroller** [comment]
No, I tend to "not carring" whether you have a conventional or a compound trigger in this case.

**Comment by PhilippSalvisberg** [comment]
Based on the feedback I think we should not include this rule
