### ISSUE TITLE
New Rule: no unused assigned values

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#48]
**Language Usage / Variables & Types / General**
Avoid assigning values to local variables that are not used by a subsequent statement

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-1854)

**Dead stores should be removed**

A dead store happens when a local variable is assigned a value that is not read by any subsequent instruction. Calculating or retrieving a value only to then overwrite it or throw it away, could indicate a serious error in the code. Even if it's not an error, it is at best a waste of resources. Therefore all calculated values should be used.

**Noncompliant Code Example**

```sql
declare
  my_user VARCHAR2(30);
  my_date VARCHAR2(30);
begin
  my_user := user();
  my_date := sysdate();
  dbms_output.put_line('User:' || my_user || ', date: ' || my_user);
end;
```

**Compliant Solution**

```sql
declare
  my_user VARCHAR2(30);
  my_date VARCHAR2(30);
begin
  my_user := user();
  my_date := sysdate();
  dbms_output.put_line('User:' || my_user || ', date: ' || my_date);
end;

```

**Comment by PhilippSalvisberg** [comment]
From my point of view this should be handled by [G-1030](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/1-general/g-1030/). 

However, PL/SQL Cop does not report a G-1030 for `my_date`. I consider this a PL/SQL Cop bug. The description of [G-1030](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/1-general/g-1030/) should be extended to cover this case as well.

**Comment by silviomarghitola** [comment]
G-1030 handles variables that are not used at all. This rule handles variables, that are used (assigned a value), but having assigned a value are no more touched.

**Comment by PhilippSalvisberg** [comment]
I know. I'm thinking about, if this case should not be handled by G-1030 as well. The reason is, that the Eclipse IDE does not distinguish between these two cases:

![image](https://user-images.githubusercontent.com/3883171/58962232-0d12bd00-87ab-11e9-8226-a957396842cd.png)

**Comment by PhilippSalvisberg** [comment]
Based on the discussion in #22 and #40 where we tend to split a rule into multiple rules with clearer meaning ans cope, I think now, that it is most probably also a good idea to distinguish between 

- variables that are declared but never used (G-1030) 
- variables that are declared, assigned a value, but never read (this rule)

It will help the developer to more quickly understand what is wrong. And that is a good thing.
