### ISSUE TITLE
New Rule: no obsolete jump statements

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#49]
**Language Usage / Control Structures / Flow Control**
Avoid using jump statements that direct the flow to the default direction

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-3626)

**Jump statements should not be redundant**

Jump statements, such as RETURN and CONTINUE let you change the default flow of program execution, but jump statements that direct the control flow to the original direction are just a waste of keystrokes.

**Noncompliant Code Example**

```
CREATE PROCEDURE print_numbers AS
BEGIN
  FOR i in 1..4 LOOP
    DBMS_OUTPUT.PUT_LINE(i);
    CONTINUE;
  END LOOP;
  RETURN;
END;
```

**Compliant Solution**

```
CREATE PROCEDURE print_numbers AS
BEGIN
  FOR i in 1..4 LOOP
    DBMS_OUTPUT.PUT_LINE(i);
  END LOOP;
END;
```

**Comment by PhilippSalvisberg** [comment]
If we say we should not use `GOTO`s (see [G-4310](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/4-control-structures/3-flow-control/g-4310/)) and `RETURN`s (see [G-7430](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/7-stored-objects/4-functions/g-7430/)) only at the end of a function, then we should also avoid using `CONTINUE`. 

Hence I'm thinking about changing the rule to not use `CONTINUE` at all. Thoughts?

**Comment by rogertroller** [comment]
An unconditional continue does not make sense at all...but other usages of continue are ok imho. Otherwise you would have either:
- lenghty if / else constructs 
- raises and exception handler to skip an iteration 
and here continue is much easier

**Comment by PhilippSalvisberg** [comment]
So you suggest to change the rule to 

**Never use unconditional `CONTINUE` statements**

Right? Do you have a good example where `CONTINUE` makes sense?
