### ISSUE TITLE
New Rule: never reuse labels in inner scopes

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#50]
**Language Usage / Control Structures / Flow Control**
Never reuse a label within its own scope

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-4280)

**Labels should not be reused in inner scopes**

Using the same name for multiple purposes reduces the understandability of the code and might eventually lead to bugs.

This rule verifies that no label is reused in an inner scope.

**Noncompliant Code Example**

```sql
<<foo>>
DECLARE
  a CONSTANT PLS_INTEGER := 0;
BEGIN
  <<foo>>
  DECLARE
    b CONSTANT PLS_INTEGER := 42;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('x = ' || foo.b);
  END;
END;
```

**Compliant Solution**

```sql
<<foo>>
DECLARE
  a CONSTANT PLS_INTEGER := 0;
BEGIN
  <<bar>>
  DECLARE
    b CONSTANT PLS_INTEGER := 42;
  BEGIN
    DBMS_OUTPUT.PUT_LINE('x = ' || bar.b);
  END;
END;
```

**Comment by PhilippSalvisberg** [comment]
Make sense. The scope needs to be defined. Only for tested blocks or for all blocks in a unit?

**Comment by rogertroller** [comment]
Forbid in nested blocks, avoid in blocks of a unit.

**Comment by PhilippSalvisberg** [comment]
Ok, two rules:

- Never reuse labels in inner scopes (this rule)
- Avoid reusing labels within a unit

**Comment by kibeha** [comment]
Created this rule as G-4325.

Not sure I agree with a rule on avoiding reuse within a unit - at least not within a package, where I can easily imagine wanting to use label <<process_employees>> in multiple procedures.

If within a procedure/function/type body/etc, then I could accept it, even though I still think I can want to have multiple identical non-nested labels at different places in the code.

I'll think about and maybe make a separate issue for that.
