### ISSUE TITLE
New Rule: no unused labels

### ISSUE THREAD

**Issue by silviomarghitola** [Trivadis/plsql-and-sql-coding-guidelines#53]
**Language Usage / General**
Avoid labels that are not used after declaration

from [SonarQube](https://rules.sonarsource.com/plsql/type/Code%20Smell/RSPEC-1065)

**Unused labels should be removed**

If a label is declared but not used in the program, it can be considered as dead code and should therefore be removed.

This will improve maintainability as developers will not wonder what this label is used for.

**Noncompliant Code Example**

```sql
<<foo>>
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello, world!');
END;
```

**Compliant Solution**

```sql
BEGIN
  DBMS_OUTPUT.PUT_LINE('Hello, world!');
END;
```

**Comment by PhilippSalvisberg** [comment]
I do not agree. A label helps to describe the content formally. It does not matter if the label is referred later. However, in some cases it might be better to move the code out into own procedures and call them. This is better than an series of named sub-blocks. But that's another story.

Furthermore this rule contradicts our guideline [G-1010](https://trivadis.github.io/plsql-and-sql-coding-guidelines/master/4-language-usage/1-general/g-1010/) where we explicitly state that you should label sub-blocks. I'm aware that the examples above are not sub-blocks, but still forcing to remove a label, which is a kind of comment, is a bad thing IMHO.
