### ISSUE TITLE
Update (change?) Rule: All code should be in lower case

### ISSUE THREAD

**Issue by RichardSoule** [Trivadis/plsql-and-sql-coding-guidelines#57]
Existing Rule 1: Keywords are written uppercase, names are written in lowercase.

Science teaches us that this isn't as good as just having all code in lower case.  In the very old days when every code editor was black on white (or green on black, or amber on black) this could 'help' us by delineating keywords. However, these days just about every editor does keyword coloring/highlighting so this isn't the 'help' that it once was. See things like: https://uxmovement.com/content/all-caps-hard-for-users-to-read/

If you adopt this standard then you'll spend a lot of time using shift lock and/or holding down your shift key... And for zero gain. 

We use the 'All code should be in lower case' rule and it works great. Interestingly I got some new interns this week and one of them mentioned "Yeah, lower case just looks more modern. All that upper case stuff makes me think of old DBAs."

**Comment by PhilippSalvisberg** [comment]
I think we need to add a paragraph explaining that being consistent is more important. If you do not agree to these rules/guidelines you can fork the repo and amend them.

I agree, that using upper case letters to emulate syntax coloring is wrong. In the utPLSQL core  project we use lower case for everything and this works well. 

In fact there is another problem with this rule, when violating the rule "Never use ORACLE keywords as names.". This happens quite often, even by Oracle, e.g. when using these keywords as column names:

- name
- document
- content
- size
- version

Writing them in upper case letters is and feels wrong. The same thing applies to other identifier names (packages, functions, procedures). So manually applying this rule is difficult and automatically applying them leads to wrong results.

I think it is time to change that.

**Comment by S-Koell** [comment]
> I think we need to add a paragraph explaining that being consistent is more important. If you do not agree to these rules/guidelines you can fork the repo and amend them.

I agree. These guidelines shouldn't specify a specific style. Maybe a recommendation.

Coming from JAVA I would eg prefer lowercase and upper for constants.I think it is much more readable that way. But others will surely disagree ;)
