### ISSUE TITLE
Suggestion: Surrogate Key Names in Naming Conventions

### ISSUE THREAD

**Issue by RichardSoule** [Trivadis/plsql-and-sql-coding-guidelines#71]
Something like:

Surrogate Key Columns
Surrogate primary key columns should be the table name with an underscore and id appended (`_id`) unless one is using plural table names in which case it should be the singular name of the table followed by `_id`. For example: `employee_id`

Reason: Naming the surrogate primary key column the same name that it would have (at least 99% of the time) when used as a foreign key allows the use of the `using` clause in SQL which greatly increases readability and maintainability of SQL code. When each table has a surrogate primary key column named `id`, then select clauses that select multiple id columns will need aliases (more code, harder to read and maintain). Additionally, the id surrogate key column means that every join will be forced into the `on` syntax which is more error-prone and harder to read than the using clause.

Example (bad):
```
select e.id as employee_id
      ,d.id as department_id
      ,e.last_name
      ,d.name
  from employees e
  join departments d on (e.department_id = d.id);
```
Example (good):
```
select e.employee_id
      ,department_id
      ,e.last_name
      ,d.name
  from employees e
  join departments d using (department_id);
```

**Comment by PhilippSalvisberg** [comment]
Our standards do not enforce the use of surrogate keys. The reasoning regarding the `ON` clause is valid, but we rejected issue #60. As a consequence we have to reject this one also.
