### ISSUE TITLE
Rules from SonarQube

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-and-sql-coding-guidelines#80]
SonarSource has rules for PL/SQL which can be viewed here: https://rules.sonarsource.com/plsql

I don't know if these are known to this project so my questions would be:
- is there an interest to extend this project with some additional Sonar rules?
- or is this project already regarded as the "best" rules distilled from Sonar ?

**Comment by RichardSoule** [comment]
I did a massive amount of research into the various guides for writing SQL and PL/SQL out there including a (truthfully a bit quick) look through the SonarSource rules and did try to incorporate the 'best' ones, but it is very possible that I may have missed some.

There would be an interest in extending this project with some additional rules. Right now there is a bit of an internal debate on 'are there too many rules?', but personally I feel like more good stuff is always better than less good stuff.

If you notice something that is missing, please log an issue and we'll consider it.

**Comment by PhilippSalvisberg** [comment]
@silviomarghitola opened issues for potentially interesting SonarQube rules missing in the Trivadis PL/SQL & SQL Coding Guidelines.

Here are some examples which we decided to include:
- #44 Boolean checks should not be inverted
- #45 Boolean literals should not be redundant
- #50 Labels should not be reused in inner scopes

And here are some examples of rules we do not plan to include:
- #51 Large item lists should not be used with "IN" clauses
- #52 SQL EXISTS subqueries should not be used
- #53 Unused labels should be removed

And there are also rules where the discussion is still open and where we haven't decided yet. Here are some examples:
- #46 no SELECT *
- #43 An "ORDER BY" direction should be specified explicitly
- #38 "LIKE" clauses should not be used without wildcards

See https://github.com/Trivadis/plsql-and-sql-coding-guidelines/issues?q=%3A%22New+Rule%22+in%3Atitle+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+ for a complete list. Please comment if you find time. This will help us to decide faster. Thanks.
