### ISSUE TITLE
Complexity Analysis page shows [Math Processing Error] in HTML site, but correct in PDF

### ISSUE THREAD

**Issue by kibeha** [Trivadis/plsql-and-sql-coding-guidelines#83]
Mathematic symbols on the Complexity Analysis page shows [Math Processing Error] in HTML site:

https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/5-complexity-analysis/complexity-analysis/

![image](https://user-images.githubusercontent.com/8858000/90005338-59069f00-dc97-11ea-94e3-63180beeb1e6.png)

But in the PDF page 131-133 it's okay:

https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/9-appendix/PLSQL-and-SQL-Coding-Guidelines.pdf

![image](https://user-images.githubusercontent.com/8858000/90005487-92d7a580-dc97-11ea-815e-e46cbf55e7aa.png)

**Comment by PhilippSalvisberg** [comment]
There is for sure something wrong. I tried Chrome, Safari, Firefox, Edge, Internet Explorer. All look like this:

![image](https://user-images.githubusercontent.com/3883171/90006281-e72f5500-dc98-11ea-9e1b-d82c7d3f9583.png)

Which is better, but still wrong.

What browser are you using?

**Comment by kibeha** [comment]
I'm using Chrome Version 84.0.4147.125 (Official Build) (64-bit)
Weird part is that this link  https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/5-complexity-analysis/complexity-analysis/  showed the error I screendumped before.
But when I open the same link _now_, it works correctly?
And I haven't even re-started my browser :-)
Firefox and Edge also show correct now?

**Comment by PhilippSalvisberg** [comment]
I guess it was a temporary problem cause by

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```

Looks good now in all browsers from my side.

**Comment by kibeha** [comment]
Yes, googling seems to indicate some problem with caching of MathJax library.

Most likely serverside hickup of MathJax.

Closing...
