### ISSUE TITLE
New Rule: Avoid multiple DML events per trigger.

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-and-sql-coding-guidelines#84]
Connor McDonald posted a video on LinkedIn named [When MORE triggers means better performance!](https://www.linkedin.com/posts/connor-mcdonald-australia_when-more-triggers-means-better-performance-activity-6711166117861298176-6su2).

He explains that multiple DML events per trigger can cause additional locks and therefore performance issues. The solution is to define a trigger per event (or avoid triggers if possible of course). 

I think this would make a fine rule and it is easy to check.

**Comment by kibeha** [comment]
Makes sense. Will make a rule for this.
