### ISSUE TITLE
Add "Unsupported in PL/SQL Cop Validators" explanation and usage

### ISSUE THREAD

**Issue by kibeha** [Trivadis/plsql-and-sql-coding-guidelines#88]
I like this additional property! 👍

_Originally posted by @PhilippSalvisberg in https://github.com/Trivadis/plsql-and-sql-coding-guidelines/pull/86#discussion_r490272189_

**Comment by kibeha** [comment]
!!! missing "Unsupported in PL/SQL Cop Validators" should be added to introduction.md. Probably not under "Severity of the rule". Maybe an addition chapter.

The following rules are currently not supported by a PL/SQL Cop validator:

G-3160 (cannot identify type of a column)
G-5010 (cannot identify logging framework and where it should be applied)
G-8410 (cannot identify where an application lock would make sense)
G-8510 (cannot know where the use of application_info is sensible)
They should be tagged with "!!! missing "Unsupported in PL/SQL Cop Validators"

**Comment by PhilippSalvisberg** [comment]
I missed the G-3170 in the previous list. Guidelines without a validator check are documented here https://github.com/Trivadis/plsql-cop-cli/blob/main/validator-limitations.md#guidelines (incl. the reason).

**Comment by kibeha** [comment]
Thanks for the link, very helpful 👍
