### ISSUE TITLE
Add version selector in HTML site.

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-and-sql-coding-guidelines#99]
The recent versions of [mike](https://github.com/jimporter/mike) supports the material theme. See also this discussion: https://github.com/squidfunk/mkdocs-material/issues/770#issuecomment-590148613 . We use the latest version in the current docker image v2.2. So technically this should work now with some configuration changes (to be tested).

Currently mike is used to deploy different versions in dedicated directories in the `gh-pages` branch only. The theme is left as is. In a static index.html a redirect is defined to the most recent version. The user may guess based on the URL how to access other versions. However, it would be nice to have a version selector (where currently the version number is displayed). User-friendlier.

Example sites using a version selector (other themes): 
- https://jimporter.github.io/mettle/latest/
- https://jimporter.github.io/bfg9000/latest/

**Comment by PhilippSalvisberg** [comment]
@kibeha I could do that, if you like.

**Comment by kibeha** [comment]
Much appreciated, thanks @PhilippSalvisberg :-)
